"""create investment schema

Revision ID: 747fcf8a991e
Revises: 
Create Date: 2026-10-03 03:09:05.379854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '747fcf8a991e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('institution', 'name', name='uq_accounts_institution_name')
    )
    op.create_index('ix_accounts_institution', 'accounts', ['institution'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange', sa.String(length=30), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin'),
    sa.UniqueConstraint('symbol', 'exchange', name='uq_assets_symbol_exchange')
    )
    op.create_index('ix_assets_asset_type', 'assets', ['asset_type'], unique=False)
    op.create_index('ix_assets_symbol', 'assets', ['symbol'], unique=False)
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'quote_currency', 'rate_date', 'source', name='uq_fx_rates_pair_date_source')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('import_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('contributed_capital', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('gain', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('return_percentage', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_at', 'source', 'currency', name='uq_portfolio_snapshots_date_source_currency')
    )
    op.create_index('ix_portfolio_snapshots_snapshot_at', 'portfolio_snapshots', ['snapshot_at'], unique=False)
    op.create_table('account_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('cash_value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'snapshot_at', 'source', name='uq_account_snapshots_account_date_source')
    )
    op.create_index('ix_account_snapshots_snapshot_at', 'account_snapshots', ['snapshot_at'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'price_date', 'source', name='uq_prices_asset_date_source')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('commission', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('taxes', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('other_fees', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_transactions_source_external_id')
    )
    op.create_index('ix_transactions_account_trade_date', 'transactions', ['account_id', 'trade_date'], unique=False)
    op.create_index('ix_transactions_asset_trade_date', 'transactions', ['asset_id', 'trade_date'], unique=False)
    op.create_index('ix_transactions_source', 'transactions', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_source', table_name='transactions')
    op.drop_index('ix_transactions_asset_trade_date', table_name='transactions')
    op.drop_index('ix_transactions_account_trade_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('prices')
    op.drop_index('ix_account_snapshots_snapshot_at', table_name='account_snapshots')
    op.drop_table('account_snapshots')
    op.drop_index('ix_portfolio_snapshots_snapshot_at', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_table('import_batches')
    op.drop_table('fx_rates')
    op.drop_index('ix_assets_symbol', table_name='assets')
    op.drop_index('ix_assets_asset_type', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_accounts_institution', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
